export const GET_LIST_MOVIE_REDUCER = 'GET_LIST_MOVIE_REDUCER';
export const SET_MOVIE_SHOWING_REDUCER = 'SET_MOVIE_SHOWING_REDUCER';
export const SET_MOVIE_COMMING_SOON_REDUCER = 'SET_MOVIE_COMMING_SOON_REDUCER';