export const SET_LIST_TICKET_ROOM_REDUCER = 'SET_LIST_TICKET_ROOM_REDUCER';
export const SET_LIST_CHAIR_BOOKING_REDUCER = 'SET_LIST_CHAIR_BOOKING_REDUCER';
export const RESET_LIST_CHAIR_BOOKING = 'RESET_LIST_CHAIR_BOOKING';
export const MOVE_TAB_TICKET_BOOKING_RESULTS = 'MOVE_TAB_TICKET_BOOKING_RESULTS';
export const CHANGE_TAB = 'CHANGE_TAB';
export const SET_CHAIR_USER_OTHER_BOOKING = 'SET_CHAIR_USER_OTHER_BOOKING';