export const SET_INFO_USER_LOGIN_REDUCER = 'SET_INFO_USER_LOGIN_REDUCER';
export const SET_INFO_ACCOUNT_REDUCER = 'SET_INFO_ACCOUNT_REDUCER';
export const SET_LIST_USER_REDUCER = 'SET_LIST_USER_REDUCER';
export const SET_LIST_TYPE_USER_REDUCER = 'SET_LIST_TYPE_USER_REDUCER';
export const SET_USER_EDIT_REDUCER = 'SET_USER_EDIT_REDUCER';